---
# This role installs and sets up keepalived

- name: Install keepalived
  yum: name=keepalived state=present
  tags: keepalived
  notify: restart keepalived

- name: Configurar configuració de keepalived
  template: src=keepalived.conf.j2 dest=/etc/keepalived/keepalived.conf
  tags: keepalived
  notify: restart keepalived

- name: Start keepalived
  service: name=keepalived state=running
  tags: keepalived
